### ISSUE TITLE
Issues with the `feat/inclusion` branch

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-template-editor#992]
While testing the branch, I ran into one minor, and a major issue.
These are:
1) Minor issue: when starting with gulp, this warning is shown on the shell console:
```
app/scripts/app.js
  line 107  col 34  'arrow function syntax (=>)' is only available in ES6 (use 'esversion: 6').
  ⚠  1 warning
```
while this is not a showstopper, might be nice not to have it here

2) Major issue. This is actually a showstopper because prevents the frontend to be used properly:
While loading the app in the browser, this is shown in the browser console:
```
artifact-selector.js:1 ERROR Error: The selector "app-root" did not match any elements
    at uu.selectRootElement (artifact-selector.js:1:120753)
    at K0 (artifact-selector.js:1:66953)
    at Co.create (artifact-selector.js:1:66991)
    at e.bootstrap (artifact-selector.js:1:103997)
    at artifact-selector.js:1:101850
    at Array.forEach (<anonymous>)
    at e._moduleDoBootstrap (artifact-selector.js:1:101837)
    at artifact-selector.js:1:101539
    at v.invoke (artifact-selector.js:1:240483)
    at Object.onInvoke (artifact-selector.js:1:94969)
```

The problem that I've seen on my system is that while the type filters are all in the "on" state, only the elements are shown on the right:

<img width="1017" alt="Screenshot 2024-05-24 at 1 54 28 PM" src="https://github.com/metadatacenter/cedar-template-editor/assets/14225187/ebf675be-bb71-4028-a71e-efc663ef07b1">

If I click all the template selector twice, everything will be properly displayed:

<img width="651" alt="Screenshot 2024-05-24 at 1 55 16 PM" src="https://github.com/metadatacenter/cedar-template-editor/assets/14225187/a4d57e58-636f-4739-9fa0-74c7b56f0e4f">

After a reload, the first state shows up again.

**Comment by muakdogan** [comment]
@egyedia thanks for reporting these. I'm aware of these issues will fix them before the merge.
